### ISSUE TITLE
allow to change background and text colour

### ISSUE THREAD

**Issue by mschaaf** [monich/harbour-books#30]

**Comment by hsjpekka** [comment]
How about using ambience-settings? Semi-transparent background and Theme.highlightColor for fonts.

**Comment by rinigus** [comment]
Would be great to get ability to select background and foreground colors. In particular, for me, I found that inverse color scheme (white on black) is rather sharp on the eyes. White on black not the best either. So, since preferences are rather personal, maybe we can add one more mode (light/inverted) or let the users to define base colors and allow to invert them. Probably allowing selection of the base colors would be better.

This is issue is kind of a killer for me - have to read on other devices then. Great work in general on this application, thank you!

**Comment by thigg** [comment]
@monich could you give some pointers on what needs to be done to implement this?

**Comment by monich** [comment]
> @monich could you give some pointers on what needs to be done to implement this?

That reminds me that I actually had some code already written for that, let me see if I can dig it up and get it to work properly...

**Comment by thigg** [comment]
That would be amazing. My eyes are just way more happy  when I can read on a solarized color scheme.

Am Montag, 26. September 2022 schrieb Slava Monich:
> > @monich could you give some pointers on what needs to be done to implement this?
> 
> That reminds me that I actually had some code already written for that, let me see if I can dig it up and get it to work properly...
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monich/harbour-books/issues/30#issuecomment-1257313416
> You are receiving this because you commented.
> 
> Message ID: ***@***.***

--

**Comment by monich** [comment]
I finally dug it up and merged it. Colors will become configurable in the next release (hopefully soon).

**Comment by thigg** [comment]
That are great news, thanks for doing rhat :)

Am Montag, 10. Oktober 2022 schrieb Slava Monich:
> I finally dug it up and merged it. Colors will become configurable in the next release (hopefully soon).
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monich/harbour-books/issues/30#issuecomment-1272672959
> You are receiving this because you commented.
> 
> Message ID: ***@***.***

--

**Comment by monich** [comment]
Version 1.1.0 includes settings for custom colors:

![image](https://user-images.githubusercontent.com/5909522/194974887-c770acce-f160-4075-a3c2-36acbc3433a5.png)

**Comment by monich** [comment]
I guess this one can be considered done.
