### ISSUE TITLE
Disable display rotation

### ISSUE THREAD

**Issue by hsjpekka** [monich/harbour-books#40]
Formatting a large book takes some time. I'm currently reading a book, which opens in about 2 mins in Xperia, and more than twice that in Jolla 1. 
If I have dynamic display orientation on, accidental turning of the phone may cause a long pause in reading. Therefore I don't use dynamic orientation. And would appreciate the possibility to fix the book direction regardless of the system settings.

**Comment by monich** [comment]
Which version are you running? Version 1.0.25 should have significantly improved the loading time.

Having said that, fixed orientation makes certain amount of sense in any case.

**Comment by monich** [comment]
After you have rotated it once, it keeps the layout in memory, so the next time layout switch occurs pretty much instantly (until you change the font size or something). Since version 1.0.25 it's basically caching the layout in the internal storage, the first load (and the first rotation) is as slow as before, but after the layout has been cached, things get better.
